### ISSUE TITLE
Projects that link to external sites should have some kind of icon

### ISSUE THREAD

**Issue by yefim** [jhil/jeffanders-2022#35]
It's a bit jarring to click on a project and go to an entirely new site. I wish there was some icon that distinguished external site projects from ones where you stay on the site. I'd suggest an icon like this: 
![image](https://user-images.githubusercontent.com/1170843/156816019-6773aa44-3e68-43fe-a9d7-468afd0776b7.png)

**Comment by jhil** [comment]
Right now these show up on hover for desktop, but I'm realizing that doesn't work on mobile! I should make these permanently visible on mobile instead of relying on the hover. Thanks Yefim 💕

![Screenshot 2022-03-04 at 10 55 59 from Google Chrome](https://user-images.githubusercontent.com/2228347/156816436-09064c05-6b1b-4805-a05b-b15c9b0846bf.png)

**Comment by yefim** [comment]
I'm on desktop and I didn't notice the arrows 🙈  maybe if they're always there it will be more noticeable :)

**Comment by jhil** [comment]
Yeah this may be one of those accessibility > elegance situations. Will noodle on it.
